xmlatex update (from ximeraFirstSteps)
* use XIMERA_URL  (ie obsolete URL_XIMERA/REPO_XIMERA)
* adapt for localhost (frost-without-commit and push-force-on-serve)
* implement 'all' option (and remove Serve, which is now automatic on localhost)

diff --git a/scripts/xmlatex b/scripts/xmlatex
--- a/scripts/xmlatex
+++ b/scripts/xmlatex
@@ -84,15 +84,15 @@ else
 
     if [[ "$1" == "ximeraserver" ]]
     then    
-        echo "Starting ximera $SERVER_NAME from $SERVER_IMAGE of port $SERVER_PORT"
+        echo "Starting ximera $SERVER_NAME from $SERVER_IMAGE on port $SERVER_PORT"
         docker run --rm --name $SERVER_NAME -p 2000:$SERVER_PORT $SERVER_IMAGE
         exit
     fi
 
     echo "Restarting myself in docker (from image $DOCKER_IMAGE)"	
     [[ -n "$DEBUG" ]] && echo  \
-    docker run --env LOCAL_IP --env XIMERA_URL --env XIMERA_NAME --env GPG_KEY --env GPG_KEY_ID --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $DOCKER_IMAGE $COMMAND $*
-    docker run --env LOCAL_IP --env XIMERA_URL --env XIMERA_NAME --env GPG_KEY --env GPG_KEY_ID --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $DOCKER_IMAGE $COMMAND $*
+    docker run --env LOCAL_IP --env XIMERA_URL --env XIMERA_NAME --env GPG_KEY --env GPG_KEY_ID --env DEBUG --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $DOCKER_IMAGE $COMMAND $*
+    docker run --env LOCAL_IP --env XIMERA_URL --env XIMERA_NAME --env GPG_KEY --env GPG_KEY_ID --env DEBUG --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $DOCKER_IMAGE $COMMAND $*
     exit 
 fi
 
@@ -116,8 +116,10 @@ debug() {
 # For (dubious) historical reasons, namely some .ximeraserve's containing URL_XIMERA and REPO_XIMERA,
 # these values are used as defaults.
 # TO BE REPLACED by XIMERA_URL and XIMERA_NAME (as set in config.txt)
-: "${URL_XIMERA:=http://$LOCAL_IP:2000/}"     # default: publish to ximera-docker-instance, but 'localhost' does refer to THIS container
-: "${REPO_XIMERA:=test}"
+# : "${URL_XIMERA:=http://$LOCAL_IP:2000/}"     # default: publish to ximera-docker-instance, but 'localhost' does refer to THIS container
+# : "${REPO_XIMERA:=test}"
+: "${XIMERA_URL:=http://localhost:2000/}"     # default: publish to ximera-docker-instance, but 'localhost' does refer to THIS container
+: "${XIMERA_REPO:=test}"
 : "${NB_JOBS:=2}"
 : "${XAKE:=xake}"
 
@@ -416,9 +418,20 @@ then
         mkdir -p $(dirname ximera-downloads/"$NAME"_pdf/$file})
         cp ${file/%.tex/.pdf} ximera-downloads/${NAME}_pdf/${file/%.tex/.pdf}
     done
-elif [[ "$COMMAND" == "serve" || "$COMMAND" == "Serve" ]]
+elif [[ "$COMMAND" == "serve" || "$COMMAND" == "all" ]]
 then
-    echo "xake serve"
+    echo "Doing xake $COMMAND"
+
+    # 'all' does also bake (should not harm to do it *always*, except for VERY SPECIFIC cases,
+    #  e.g. adhoc manipulation of .html files ...)
+    if [[ "$COMMAND" = "all" ]] 
+    then
+        echo "Baking ..."
+        $XAKE --jobs $NB_JOBS bake      # Generate html files
+    fi
+
+    # If GPG_KEY_ID (and presumably GPG_KEY) are given, 
+    # ignore .ximeraserve, which should only be used for the DUMMY key ...
     if [[ -z "$GPG_KEY_ID" ]]
     then
         if [[ -f .ximeraserve ]]
@@ -427,8 +440,8 @@ then
             source .ximeraserve
 	        echo GPG_KEY_ID=$GPG_KEY_ID
 	        echo GPG_KEY=${GPG_KEY:0:10}...
-            : ${XIMERA_NAME:=$REPO_XIMERA}
-            : ${XIMERA_URL:=$URL_XIMERA}
+            # : ${XIMERA_NAME:=$REPO_XIMERA}
+            # : ${XIMERA_URL:=$URL_XIMERA}
         fi
         if [[ -z "$GPG_KEY_ID" ]]   # still no key ...
         then
@@ -452,28 +465,38 @@ then
         echo "$GPG_KEY" | base64 --decode > .gpg # decode the base64 gpg key
         debug "Decoded in .gpg: $(ls -al .gpg)"
         debug "Starting gpg -q $VERBOSE --import .gpg"
-        gpg -q $VERBOSE --import .gpg  || error "gpg --import failed (from key itself in variable)"
+        gpg -q $VERBOSE --import .gpg  || echo "gpg --import failed (from key itself in variable)"
         rm .gpg # remove the gpg key so it is certainly not cached
     fi
     [[ -n "$DEBUG" ]] && gpg --list-keys
 
 
+    if [[ "$XIMERA_URL" =~ http://localhost ]]
+    then
+        # On localhost, don't care too much about consistency/security 
+        export XM_PUSH_FORCE=1
+        export XM_FROST_WITH_UNCOMMITTED_CHANGES=1
+        export XM_PUBLISH_WITH_DUMMY_KEY=1
+    fi
+
+
+
     if [[ "$GPG_KEY_ID" =~  ^215FC33FAB44D ]]
     then
-        if [[ "$XIMERA_URL" =~ http://localhost ]]
-        then    
-            echo "Try to register with dummy gpg key"
-        else
+        if [[ -n "$XM_PUBLISH_WITH_DUMMY_KEY" ]]
+        then
+            echo "Publishing to $XIMERA_URL with dummy key."
+        else   
             error "I won't publish to $XIMERA_URL with a dummy GPG key." 
         fi 
     else
-	    debug "Not using dummy key ($GPG_KEY_ID)"
+	    debug "We're not using the dummy key, but ${GPG_KEY_ID:0:10}"
     fi
 
     debug "KEYSERVER gpg $VERBOSE --keyserver $XIMERA_URL --send-key $GPG_KEY_ID"
     gpg -q $VERBOSE --keyserver $XIMERA_URL --send-key "$GPG_KEY_ID" || echo "WARNING: gpg sendkey failed (to url $XIMERA_URL), which is no problem if this key is already there"
     
-    echo "xake NAME: on $XIMERA_URL set name to $XIMERA_NAME"
+    echo "Doing xake NAME (on $XIMERA_URL set name to $XIMERA_NAME)"
     debug "xake NAME: $XAKE -U $XIMERA_URL -k $GPG_KEY_ID name $XIMERA_NAME"
     $XAKE -U $XIMERA_URL -k "$GPG_KEY_ID" name "$XIMERA_NAME" || error "xake name failed" 
 
@@ -483,15 +506,15 @@ then
 #    git branch -D master || true    #ignore error
 #    git checkout -B master # doe alsof we op master zitten
 
-    FROST="frost"
-    [[ "$COMMAND" == "Serve" ]] && FROST="Frost"
-    echo "$XAKE $FROST"
-    # type $XAKE
-    # frost builds metadata.json and tag for publishing
-    # Frost dosz the same, but ignores 'not committed' errors (with xake version of 2024-10)
-    $XAKE $FROST || error "xake $FROST failed, you might want to use Serve"  
+    : "${FROST:=frost}"
+    [[ -n "$XM_FROST_WITH_UNCOMMITTED_CHANGES" ]] && FROST="Frost"
+    # '**F**rost' allows frosting with uncommitted changes...? Should not be done 'in production'.
+    # 'xake frost' builds metadata.json and tag for publishing
+    # 'xake Frost' does the same, but ignores 'not committed' errors (with xake version of 2024-10)
 
-    echo "xake SERVE"
+    echo "Doing $XAKE $FROST"
+    $XAKE $FROST || error "xake $FROST failed, you might want to set XM_FROST_WITH_UNCOMMITTED_CHANGED (e.g. in config.txt)"  
+
     if [[ -n "$DEBUG" ]]
     then
         echo "git status:"
@@ -503,13 +526,21 @@ then
         echo "git remote -v:"
 	    git remote -v
     fi
-    $XAKE serve 2>&1 || error "xake serve failed"  # Upload files = push tag
+    echo "Doing xake serve"
+    $XAKE serve  2>&1  || error "xake serve failed"  # Upload files = push tag
+    #  NOTE: as of 2024-10, xake serve does not always return a correct errorcode !!!
 
+    # HACK to OVERWRITE an already published revision
+    if [[ -n "$XM_PUSH_FORCE" ]]
+    then
+       REV=$(git rev-parse HEAD)
+       echo  FORCING PUSH: git push -f ximera publications/$REV
+       git push -f ximera publications/$REV
+    fi
 
     # Check if the file exists
     if [ ! -d ".git" ]; then
-        echo "Error: Folder '$.git' not found."
-        exit 1
+        error "Folder '.git' not found."
     fi
 
     # Get the owner and group of .git
@@ -518,18 +549,12 @@ then
     if [[ "$owner_group" != "0:0" ]]
     then
         # Change the ownership of all files in the current directory
+        echo "Changing ownership of all files in .git to $owner_group."
         chown -R "$owner_group" .git
-        echo "Ownership of all files in the current directory has been changed to $owner_group."
     fi
-
-elif [[ "$COMMAND" == "compileNC" ]]   # NC = NoCheck  (OBSOLETE!!)
-then
-    shift
-    echo "xake --skip-mathjax compile $* (with --skip-mathjax ...)"
-    $XAKE --skip-mathjax compile $*
 else
     # Hope that 'xake $*' was intended ...; if not, xake will complain.
-    echo "Starting xake $*"
+    echo "Starting $XAKE $*"
     $XAKE $*
 fi
 
