update xmlatex.full (o.a. fix compileNC)

diff --git a/scripts/xmlatex b/scripts/xmlatex
--- a/scripts/xmlatex
+++ b/scripts/xmlatex
@@ -1,10 +1,16 @@
 #!/bin/bash
 #
+# This script starts a docker container and run (a wrapper-script around) ximera's 'xake' command
+#
 # Usage: 
 #   xmlatex bake
 #   xmlatex compile test/myximerafile.tex
-#   xmlatex serve
+#   xmlatex serve     # this will also run 'xake frost'
 #   xmlatex -i bash   # gets a bash-shell INSIDE the container
+#
+# Advanced usage
+#   XAKE_IMAGE=ghcr.io/ximeraproject/xake2023:latest xmlatex compile demo.tex    # use a different docker image
+#   COMMAND=pdflatex xmlatex demo.tex                                            # do not run the xake-wrapper, but $COMMAND
 #
 # This script
 #  - starts a xake docker container (unless we're already IN a container)
@@ -12,22 +18,23 @@
 #  - that (presumably) starts xake with the arguments passed to this script
 #  - optionally gets you a shell inside the container
 #  - optionally automates lots of other things
-
+#
 # Note: set environment variable 'export DEBUG=1' and/or use -d option for debugging/tracing
-
+#
 #
 # Set some defaults
 #
 # default docker image to run; overwrite with 'export XAKE_IMAGE=myxake:0.1'
-: "${XAKE_IMAGE:=ghcr.io/ximeraproject/xake2019:latest}"
-#  : "${XAKE_IMAGE:=ghcr.io/ximeraproject/xake2023:v2.1.1}"    # alternative ...
-
+: "${XAKE_IMAGE:=ghcr.io/ximeraproject/xake2019:latest}" 
+#  : "${XAKE_IMAGE:=ghcr.io/ximeraproject/xake2019:latest}"
+#
 # Which folder to mount INSIDE the container, under /code  (use with care: it should contain a build.sh !)
 : "${MOUNTDIR:=$(pwd)}"
-
-# Which script to start inside the container; only usefull for OLD xake-images, which used a now obsolete build.sh script
-: "${XMLATEX:=xmlatex}"
-# : "${XMLATEX:=./build.sh}"
+#
+# Which script to start inside the container; 
+: "${COMMAND:=xmlatex}"
+# : "${COMMAND:=pdflatex}"     # skip xmlatex inside the container, and directly run a specific command ...    
+# : "${COMMAND:=./build.sh}"   # only usefull for OLD xake-images, which used a now obsolete build.sh script
 
 
 if [[ -f /.dockerenv ]]  
@@ -41,7 +48,8 @@ else
 
     if [[ "$1" == "-i" ]]
     then
-        INTERACTIVE="-it"
+        INTERACTIVE="-it"  # start an interactive docker session (i.e. with a terminal attached)
+        shift 
     fi 
 
     # LOCAL_IP is only needed if you want to serve to a ximeraServer on your localhost; do NOT use URL_XIMERA when using LOCAL_IP
@@ -52,14 +60,15 @@ else
     fi
 
     echo "Restarting myself in docker (from image $XAKE_IMAGE)"	
-    [[ -n "$DEBUG" ]] && echo  docker run --env LOCAL_IP --env URL_XIMERA --env REPO_XIMERA --env GPG_KEY --env GPG_KEY_ID --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $XAKE_IMAGE $XMLATEX $*
-    docker run --env LOCAL_IP --env URL_XIMERA --env REPO_XIMERA --env GPG_KEY --env GPG_KEY_ID --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $XAKE_IMAGE $XMLATEX $*
+    [[ -n "$DEBUG" ]] && echo  \
+    docker run --env LOCAL_IP --env URL_XIMERA --env REPO_XIMERA --env GPG_KEY --env GPG_KEY_ID --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $XAKE_IMAGE $COMMAND $*
+    docker run --env LOCAL_IP --env URL_XIMERA --env REPO_XIMERA --env GPG_KEY --env GPG_KEY_ID --network host --rm $INTERACTIVE --mount type=bind,source=$MOUNTDIR,target=/code $XAKE_IMAGE $COMMAND $*
     exit 
 fi
 
 # We're for sure running in a container now
 
-echo "Starting $0 $* (inside container) "
+echo "Starting $0 $*"
 
 # utility functions for errorhandling/debugging (and logging to be added ...?)
 error() {
@@ -103,9 +112,9 @@ EOF
         ;;
     d ) DEBUG=1 
         XAKE="$XAKE -v"
-        ;;
-    s ) XAKE="$XAKE --skip-mathjax"
       ;;
+    s ) XAKE="$XAKE --skip-mathjax"
+      ;;      
     \? ) echo "Usage: build [-h] [-i] <commands>"
 	 exit 1
       ;;
@@ -162,13 +171,9 @@ if [[ -d .ximera_local ]]; then
     cp -r .ximera_local/* /root/texmf/tex/latex/ximeraLatex
 fi
 
-# Hack: recent versions of xake start THIS VERY SCRIPT again (instead of hardcoded commands inside the xake-executable)
-# Some OLD (KULeuven) versions used an adhoc script 'mypdflatex' instead, which sometimes was not 'executable'
-[[ -f mypdflatex ]] && chmod +x mypdflatex
+[[ -n "$DEBUG" ]]  && ls -al /root/texmf/tex/latex/ximeraLatex/
 
-# Make sure the current ('base')-directory is in the path. 
-# This allows for LOCAL versions of xmlatex or other things to OVERWRITE whatever is in the container.
-# To be used with care ...
+# Extend the path, so that commands in the rootfolder OVERWRITE what is in the container
 PATH=$(pwd):$PATH
 
 # Longer lines in pdflatex output
@@ -224,6 +229,7 @@ then
     #  It removes spurious trailing dashed in the filename of included figures/images in the html files ...
     debug Fixing svg filenames in ${FILE%.tex}.html
     sed -i.bak 's/-figure\([0-9]*\)-\.svg/-figure\1.svg/' ${FILE%.tex}.html
+    exit 0   # DUBIOUS
 elif [[ "$COMMAND" == "texPdf" ]]
 then
     # THIS OPTION IS CALLED BY xake (versions >= 2.1.1) (and ONLY with this option, at least in xake 2.1.1...!)
@@ -260,7 +266,7 @@ then
         fi
     done
     echo "Baking other files ..."
-    $XAKE --jobs $NB_JOBS bake # Genereer de html files
+    $XAKE --jobs $NB_JOBS bake      # Generate html files
 elif [[ "$COMMAND" == "cleanstandaard" ]]
 then
     NAME=standaard
@@ -348,14 +354,14 @@ then
 elif [[ "$COMMAND" == "serve" ]]
 then
     echo "xake serve"
-
-
     if [[ -z "$GPG_KEY_ID" ]]
     then
         if [[ -f .ximeraserve ]]
         then
             echo "Using settings from .ximeraserve"
             source .ximeraserve
+	        echo GPG_KEY_ID=$GPG_KEY_ID
+	        echo GPG_KEY=${GPG_KEY:0:10}...
         fi
         if [[ -z "$GPG_KEY_ID" ]]   # still no key ...
         then
@@ -365,24 +371,24 @@ then
     debug "Loading GPG Key"
     if [[ -f "$GPG_KEY" ]]
     then
-        echo "Importing private key from $GPG_KEY"
+        echo "Importing private key from GPG_KEY=$GPG_KEY"
         # First try import as 'binary' file, if this fails, try base64 decoded version...
         if ! gpg -q $VERBOSE --import $GPG_KEY 
         then
             debug "Importing base64-encode private key from $GPG_KEY"
             cat $GPG_KEY | base64 --decode > .gpg # decode the base64 gpg key
-            gpg -q $VERBOSE --import .gpg ||  error "gpg --import failed (encoded key)"
+            gpg -q $VERBOSE --import .gpg ||  error "gpg --import failed (from encoded key in file)"
             rm .gpg # remove the gpg key so it is certainly not cached
         fi
     else 
-        echo  "Importing private key in variable GPG_KEY"
-        echo "$GPG_KEY" >.gpg # | base64 --decode > .gpg # decode the base64 gpg key
-        gpg -q $VERBOSE --import .gpg  || error "gpg --import failed (key itself in variable)"
+        echo  "Importing (encoded) private key from variable GPG_KEY"
+        echo "$GPG_KEY" | base64 --decode > .gpg # decode the base64 gpg key
+        gpg -q $VERBOSE --import .gpg  || error "gpg --import failed (from key itself in variable)"
         rm .gpg # remove the gpg key so it is certainly not cached
     fi
     [[ -n "$DEBUG" ]] && gpg --list-keys
     debug "KEYSERVER gpg $VERBOSE --keyserver $URL_XIMERA --send-key $GPG_KEY_ID"
-    gpg -q $VERBOSE --keyserver $URL_XIMERA --send-key "$GPG_KEY_ID" || echo "WARNING: gpg sendkey failed (to url $URL_XIMERA)"
+    gpg -q $VERBOSE --keyserver $URL_XIMERA --send-key "$GPG_KEY_ID" || echo "WARNING: gpg sendkey failed (to url $URL_XIMERA), which is no problem if this key is already there"
     
     echo "xake NAME: on $URL_XIMERA set name to $REPO_XIMERA"
     debug "xake NAME: $XAKE -U $URL_XIMERA -k $GPG_KEY_ID name $REPO_XIMERA"
@@ -412,10 +418,11 @@ then
     $XAKE serve 2>&1 || error "xake serve failed"  # Upload files = push tag
 elif [[ "$COMMAND" == "compileNC" ]]   # NC = NoCheck ...
 then
-    echo "xake $* (with --skip-mathjax ...)"
-    $XAKE --skip-mathjax $*
+    shift
+    echo "xake --skip-mathjax compile $* (with --skip-mathjax ...)"
+    $XAKE --skip-mathjax compile $*
 else
-    # Hope that 
+    # Hope that 'xake $*' was intended ...; if not, xake will complain.
     echo "Starting xake $*"
     xake $*
 fi
